service_aware:
  services:
    jsm.serializer_bundle.serializer:
      interface: "Bit3\\Symfony\\ServiceAwareBundle\\JMS\\SerializerBundle\\SerializerAwareInterface"
      method:    "setSerializer"
      service:   "jms_serializer"
